import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getGoogleAuth, gmailClient } from "@/lib/google-client";

export const dynamic = "force-dynamic";

function headerValue(headers: { name?: string | null; value?: string | null }[] | undefined, name: string) {
  return headers?.find((h) => h.name?.toLowerCase() === name.toLowerCase())?.value ?? "";
}

// GET → cached AI-written overview of the unread inbox (generated by the
// Hermes bridge via the `hermes` CLI — same Claude Code auth as everything
// else Hermes does, no separate API key).
export async function GET() {
  const row = await prisma.dataStore.findUnique({ where: { key: "gmail-overview" } });
  const data = (row?.data as { summary?: string; total?: number; generatedAt?: string } | null) ?? null;
  return NextResponse.json(data ?? { summary: null, total: null, generatedAt: null });
}

// POST → gather unread email metadata (from/subject/snippet, read-only) and
// queue a Hermes request that writes a prose overview back to DataStore.
// Skips queuing if one is already queued/running so refresh spam is a no-op.
export async function POST() {
  const auth = await getGoogleAuth();
  if (!auth) return NextResponse.json({ error: "Gmail not connected" }, { status: 400 });

  const pending = await prisma.agentRequest.findFirst({
    where: { kind: "gmail.summarize", status: { in: ["queued", "running"] } },
  });
  if (pending) return NextResponse.json({ request: pending, queued: false });

  const gmail = gmailClient(auth);
  // Gmail's messages.list `resultSizeEstimate` is an INDEX ESTIMATE for
  // search queries — it can be wildly inflated (this is why the overview
  // was showing e.g. 201 unread when the real inbox was nowhere near that).
  // The INBOX label's `messagesUnread` field is an exact, maintained counter
  // — use that as the real total instead.
  const [list, inboxLabel] = await Promise.all([
    gmail.users.messages.list({ userId: "me", q: "in:inbox is:unread", maxResults: 20 }),
    gmail.users.labels.get({ userId: "me", id: "INBOX" }),
  ]);
  const ids = list.data.messages ?? [];
  const total = inboxLabel.data.messagesUnread ?? ids.length;

  if (ids.length === 0) {
    await prisma.dataStore.upsert({
      where: { key: "gmail-overview" },
      create: { key: "gmail-overview", data: { total: 0, summary: "Inbox zero — nothing unread right now.", generatedAt: new Date().toISOString() } },
      update: { data: { total: 0, summary: "Inbox zero — nothing unread right now.", generatedAt: new Date().toISOString() } },
    });
    return NextResponse.json({ queued: false, immediate: true });
  }

  const brief = await Promise.all(
    ids.map(async (m) => {
      const msg = await gmail.users.messages.get({
        userId: "me",
        id: m.id!,
        format: "metadata",
        metadataHeaders: ["From", "Subject"],
      });
      const headers = msg.data.payload?.headers;
      return {
        from: headerValue(headers, "From"),
        subject: headerValue(headers, "Subject"),
        snippet: msg.data.snippet ?? "",
      };
    })
  );

  const listing = brief
    .map((m, i) => `${i + 1}. From: ${m.from || "unknown"} | Subject: ${m.subject || "(no subject)"} | Preview: ${m.snippet.slice(0, 160)}`)
    .join("\n");

  const prompt =
    `Summarize this inbox for the operator. Here are up to 20 of the newest unread emails (there are ${total} unread total):\n\n${listing}\n\n` +
    `Write a short spoken-style overview (3-5 sentences): group by theme (client/work, newsletters, notifications, personal), ` +
    `call out anything time-sensitive or important, skip clearly promotional mail. No headers, no markdown, no bullets — plain prose. ` +
    `Output ONLY valid JSON, no code fences, in exactly this shape: {"summary":"..."}`;

  const row = await prisma.agentRequest.create({
    data: {
      origin: "web",
      kind: "gmail.summarize",
      title: `Summarize inbox (${total} unread)`,
      prompt: JSON.stringify({ prompt, total }),
      sideEffecting: false,
      status: "queued",
    },
  });
  return NextResponse.json({ request: row, queued: true });
}
